config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins
  resources :abouts
  get 'abouts/about'
  get 'entertainment', to: 'contacts#entertainment', as: 'entertainment'
  root 'blogs#index'
  resources :blogs do
    member do 
      get 'blogs/most_popular'
      get 'blogs/blog_detail'
      get 'blogs/about'
      get 'blogs/all_blogs'      
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    validates :title, :content,length: {in: 1..140} 
    validates :title, :content, presence: true
    belongs_to :admin

    paginates_per 9
    def self.search(search)
        if search
            where('title LIKE ? or content', "%#{search}%")        
        else
            order('id desc')
        end
    end
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def about
  end

  def index
    @search = Blog.ransack(params[:q])
    @blogs = @search.result.page params[:page]
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    
    def  index
        @search = Blog.ransack(params[:q])
        @blogs = @search.result
    end

    def new 
        @search = Blog.ransack(params[:q])
        @blogs = @search.result
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    @search = Blog.ransack(params[:q])
    @blogs = @search.result
    # before_action :admin_authorize 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new,:edit,:destroy]
  # GET /blogs
  # GET /blogs.json
  def search
    @blog =Blog.search(params[:search])
  end
  def index
    # @blogs = Blog.order("created_at DESC").all   
    @search = Blog.ransack(params[:q])
        @blogs = @search.result
    if params[:q]
        # @blogs = Blog.search(params[:search]).order("created_at DESC")
        @search = Blog.ransack(params[:q])
        @blogs = @search.result
       else
        @blogs = Blog.all.order('created_at DESC')
       end
    # @movies = @search.result
    #   @search = Blog.search(params[:q])    
    #   @blogs = if params[:search]
    #     Blog.where('title LIKE ? or content LIKE ?', "%#{params[:search]}%","%#{params[:search]}%").page(params[:page])    
    #     else
    #       #@blogs = Blog.all.order('created_at desc').page params[:page]
    #       @blogs = Blog.order("created_at DESC").page(params[:page])
    #     end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  def most_popular 
    # @blogs = Blog.all
    @search = Blog.ransack(params[:q])
    @blogs = @search.result
    @blog_id = params[:blog_id]
  end

  def blog_detail 
    # @blogs = Blog.all
    @search = Blog.ransack(params[:q])
    @blogs = @search.result
    @blog_id = params[:blog_id]
  end
  def all_blogs 
    # @blogs = Blog.all
    @search = Blog.ransack(params[:q])
    @blogs = @search.result
  end
  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :image, :admin_id, :search)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  def show
  end

  def entertainment
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact, notice: 'Contact was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contacts/1
  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: 'Contact was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contacts/1
  def destroy
    @contact.destroy
    redirect_to contacts_url, notice: 'Contact was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def contact_params
      params.require(:contact).permit(:name, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @search = Blog.ransack(params[:q])
        @blogs = @search.result
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def admin_authorize
        unless current_admin and current_admin.admin == true
            redirect_to root_path, alert:"Only administrator can access this page."
        end
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    before_action :admin_authorize 
end

app/views/abouts/about.html.erb
<div class="container">
    <h3 class="text-center">About Me</h3>
    <div>
        <p>
            <%= render  "layouts/random" %>
        </p>
    </div>
</div>

app/views/abouts/index.html.erb
<div class="all-content ">
  <div class="container mb-3">
    <div class=" blog-index-card">
      <div class="">
        <div class="row row-cols-1 row-cols-md-3 ">
          <% @blogs.each do |blog| %>
          <div class="col mb-4 mt-5">
            <a href="/blogs/<%=blog.id%>/blogs/blog_detail" class="text-decoration-none text-dark">
              <div class="card recent-blog-cards">
                <%= image_tag('normal.jpg', class:"card-img all-blogs-card-img")%>
                <div class="card-body">
                  <p class="card-text"><%= blog.content%></p>
                  <p class="card-text"><small class="text-muted">Posted by : <%= blog.admin.email %> </small></p>
                </div>
              </div>
            </a>
          </div>
          <%end%>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center mb-2">
      <%= paginate @blogs %>
    </div>    
  </div>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/blogs/_cta.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card" style="width: 33.5rem;height:55vh">        
        <div class="card-body">
          <div class="row">
            <div class="col-md-3"> 
              <div class="rot">ABOUT ME</div>
            </div>
            <div class="col-md-9">
              <div class="mt-5">
                <h4 class="card-title">Life Events Blog Posts :) 
                    My name is Winter!</h4>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="/abouts/about" class="btn btn-light btn-outline-dark  rounded-pill cta-btn text-center">Read More</a>
              </div>
            </div>
          </div>            
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <a class="ctaa">
        <div class="card cta" style="width: 16rem;">
          <div class="cta-hover"></div>
          <div class="cta-card">
            <%= image_tag('normal.jpg', class:"card-img cta-image")%>
            <div class="d-flex justify-content-center">
              <div class="cta-card-btn ">
                <a href="/blogs/:id/blogs/all_blogs" onclick="window.location.href=this" class = "btn btn-light rounded-pill cta-btn smooth-scroll">Recent Posts</a>
              </div>
            </div> 
          </div>       
        </div>
    </a>
    </div>
    <div class="col-md-3">
      <div class="card cta" style="width: 16rem;">
        <div class="cta-hover"></div>
        <div class="cta-card ">
          <%= image_tag('normal.jpg', class:"card-img cta-image")%>
          <div class="d-flex justify-content-center">
            <div class="cta-card-btn ">
              <%= link_to  "Instagram", blogs_path, class:"btn btn-light rounded-pill cta-btn" ,onclick:"window.location.href=this"%>
            </div>
          </div> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true, html: { multipart: true }) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.file_field :image %>
    <%= form.hidden_field :admin_id, value:current_admin.id%>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/_latest.html.erb
<div class="card mb-3 latest-card" style="max-width: 100%;height:65vh !important;">
  <% @blogs.order("created_at DESC").limit(1).each do |blog|%>
  <div class="row no-gutters">    
      <div class="col-md-7">
        <a href="/blogs/<%=blog.id%>/blogs/blog_detail" class="text-decoration-none text-dark">
          <%if blog.image.present?%>
            <%= image_tag blog.image.url(:medium)%> 
          <%else%>
            <%= image_tag('normal.jpg', class:"card-img latest-image")%>
          <%end%>
        </a>
      </div>
      <div class="col-md-5">
        <a href="/blogs/<%=blog.id%>/blogs/blog_detail" class="text-decoration-none text-dark">
          <div class="card-body">
            <div class="latest-body ">
              <h5 class="card-title title"><%= blog.title%></h5>
              <p class="card-text"><%= blog.content%></p>
              <p class="card-text"><small class="text-muted">Posted by:<%= blog.admin.email %>  </small></p>
            </div>
          </div>
        </a>
      </div>
  </div>
  <%end%>
</div>

app/views/blogs/about.html.erb
<%= render  "abouts/about" %>

app/views/blogs/all_blogs.html.erb
<div class="all-content " >
    <div class="container mb-3" >
      <div class=" blog-index-card">
        <div class="">    
          <div class="row row-cols-1 row-cols-md-3 ">
            <% @blogs.each do |blog| %>
            <div class="col mb-4 mt-5">
              <a  href="/blogs/<%=blog.id%>/blogs/blog_detail" class="text-decoration-none text-dark">
                <div class="card recent-blog-cards">
                    <%= image_tag('normal.jpg', class:"card-img all-blogs-card-img")%>
                  <div class="card-body">
                      <p class="card-text"><%= blog.content%></p>
                      <p class="card-text"><small class="text-muted">Posted by : </small></p>
                  </div>
                </div>
              </a>
            </div>   
            <%end%>             
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/blogs/blog_detail.html.erb
<div class="all-content ">
  <div class="container mb-3">
    <div class=" blog-index-card">
      <div class="">
        <div class="row">
          <div class="col-md-8">
            <% @blogs.each do |blog| %>
            <% if  params[:id].to_i == blog.id%>
            <div class="card blog-detail-card mt-5 mb-3">
              <%= image_tag('normal.jpg', class:"card-img-top blog-detail-card-img")%>
              <div class="card-body">
                <h5 class="card-title"><%= blog.title%></h5>
                <p class="card-text"><%= blog.content%></p>
                <p class="card-text"><small class="text-muted">Posted by: <%= blog.admin.email %> </small></p>
              </div>
            </div>
            <%end %>
            <% end %>
            <a href="/blogs" class="text-decoration-none text-dark btn btn-light" onclick="window.location.href=this">Back</a>
          </div>
          <div class="col-md-4">
            <div class="card most-popular mt-5">
              <h3 class="card-title">Most Popular</h3>
              <div class="row">
                <div class="card-body">
                  <%Blog.all.limit(10).each do |blog|%>
                  <div class="row">
                    <div class="col-md-9 ">
                      <input id="most" class="most" value="0">.
                      <%= link_to  blog.title, blogs_most_popular_blog_path(blog.id, blog_id:blog.id) , class:"text-capitalize text-dark text-decoration-none most-popular-link", onclick:"window.location.href=this"%><br>
                    </div>
                    <div class="col-md-3">
                      <%= image_tag('normal.jpg', class:"card-img most-popular-card-img")%>
                    </div>
                  </div>
                  <hr>
                  <%end%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="latest minified " id="top">
  <%= render  "blogs/latest" %>
</div>
<div class="cta">
  <%= render  "blogs/cta" %>
</div>
<span id="all_blogs" class=" animated slideInUp"></span>
<div class="all-content " >
  <div class="container mb-3" >
    <div class=" blog-index-card">
      <div class="">    
        <div class="row">
          <div class="col-md-8">
            <div class="card-groups" >
              <% @blogs.limit(10).offset(1).each do |blog| %>
                <a href="/blogs/<%=blog.id%>/blogs/blog_detail" class="text-decoration-none text-dark" onclick="window.location.href=this">
                  <div class="card mb-3 mt-5 all-blogs-card" style="width: 45rem;">
                    <div class="row no-gutters">
                      <div class="col-md-5">  
                        <div class="row">
                          <div class="col-md-4">
                            <div class="line mb-2"></div>
                            <%= blog.created_at.strftime("%d %B")%>
                          </div>
                          <div class="col-md-8">
                            <%= image_tag('normal.jpg', class:"card-img all-blogs-card-img")%>
                          </div>
                        </div>                       
                      </div>
                      <div class="col-md-7">
                        <div class="card-body">
                          <h5 class="card-title title"><%= blog.title%></h5>
                          <p class="card-text"><%= blog.content%></p>
                          <p class="card-text"><%= blog.category%></p>
                          <p class="card-text"><small class="text-muted">Posted by : <%= blog.admin.email %> </small></p>
                        </div>
                      </div>
                    </div>
                  </div>
                </a>
                <hr>
              <%end%>
            </div>
          </div>
          <div class="col-md-4">     
            <div class="card most-popular mt-5">
              <h3 class="card-title">Most Popular</h3>
              <div class="row">                
                <div class="card-body">
                  <%Blog.all.limit(10).each do |blog|%>
                    <div class="row">
                      <div class="col-md-9 ">                      
                        <input id="most" class="most" value="0" >. <%= link_to  blog.title, blogs_most_popular_blog_path(blog.id, blog_id:blog.id) , class:"text-capitalize text-dark text-decoration-none most-popular-link ", onclick:"window.location.href=this"%><br>                      
                      </div>
                      <div class="col-md-3">
                        <%= image_tag('normal.jpg', class:"card-img most-popular-card-img")%>
                      </div>
                    </div>
                    <hr>
                  <%end%> 
                </div>              
              </div>            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

 

app/views/blogs/most_popular.html.erb
<div class="all-content ">
    <div class="container mb-3">
      <div class=" blog-index-card">
        <div class="">
          <div class="row">
            <div class="col-md-8">
              <% @blogs.each do |blog| %>
              <% if  params[:id].to_i == blog.id%>
              <div class="card blog-detail-card mt-5 mb-3">
                <%= image_tag('normal.jpg', class:"card-img-top blog-detail-card-img")%>
                <div class="card-body">
                  <h5 class="card-title"><%= blog.title%></h5>
                  <p class="card-text"><%= blog.content%></p>
                  <p class="card-text"><small class="text-muted">Posted by: <%= blog.admin.email %> </small></p>
                </div>
              </div>
              <%end %>
              <% end %>
              <a href="/blogs" class="text-decoration-none text-dark btn btn-light" onclick="window.location.href=this">Back</a>
            </div>
            <div class="col-md-4">
              <div class="card most-popular mt-5">
                <h3 class="card-title">Most Popular</h3>
                <div class="row">
                  <div class="card-body">
                    <%Blog.all.limit(10).each do |blog|%>
                    <div class="row">
                      <div class="col-md-9 ">
                        <input id="most" class="most" value="0">.
                        <%= link_to  blog.title, blogs_most_popular_blog_path(blog.id, blog_id:blog.id) , class:"text-capitalize text-dark text-decoration-none most-popular-link", onclick:"window.location.href=this"%><br>
                      </div>
                      <div class="col-md-3">
                        <%= image_tag('normal.jpg', class:"card-img most-popular-card-img")%>
                      </div>
                    </div>
                    <hr>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/entertainment.html.erb
<h1>Entertainment</h1>
<div class = "row">
<div class= "col-md-6">
GAMES<br>
<ul>
<li>Football</li>
<li>Basketball</li>
<li>Baseball</li>
<li>Billiard</li>
</ul>

</div>
<div class = "col-md-6">
NEWS<br>
<ul>
<li>Rwandan NEWS</li>
<li>East African</li>
<li>African</li>
<li>Others</li>
</ul>
<u>
</div>
</div>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/shared/_bottom_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light footer-nav mb-3">
  <div class="d-flex justify-content-center "> 
    <div class="row">
      <div class="col-md-6">
        <div class="nav-item nav-link">GetPosted © 2019 ALL RIGHTS RESERVED.</div>
      </div>
      <div class="col-md-6">
        <div class="navbar-nav text-light foot">
          <a class="nav-item nav-link active"  onclick="window.location.href=this" href="/blogs">HOME </a>
          <a class="nav-item nav-link" onclick="window.location.href=this"  href="/">LIFE</a>
          <a class="nav-item nav-link" onclick="window.location.href=this"  href="/">ENTERTAINMENT</a>
          <a class="nav-item nav-link" onclick="window.location.href=this"  href="/abouts/about">ABOUT</a>
          <a class="nav-item nav-link" onclick="window.location.href=this"  href="/">CONTACTS</a> 
          
          <!-- <a href="/#top" class=" btn nav-item nav-link top" >Top</a>      -->
        </div>
      </div>
    </div>     
    
  </div>  
</nav> 

app/views/shared/_topnav.html.erb
<div class="d-flex justify-content-center navbar navy">
  <nav class="navbar navbar-expand-lg navbar-light ">
      <div class="d-flex justify-content-center">
          <!-- <a class="nav-item nav-link" href="#"><img src="https://img.icons8.com/ios-glyphs/30/000000/menu-rounded.png"></a> -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link active"  onclick="window.location.href=this" href="/blogs">HOME <span class="sr-only">(current)</span></a>
              <a class="nav-item nav-link" onclick="window.location.href=this"  href="/">LIFE</a>
              <%= link_to 'ENTERTAINMENT', entertainment_path %></a>
              <a class="nav-item nav-link" onclick="window.location.href=this"  href="/abouts/about">ABOUT</a>
              <a class="nav-item nav-link" onclick="window.location.href=this"  href="/"><%= link_to 'CONTACTS', contacts_path %></a>
              
              <!-- <div class="search-area"> -->
                <i id="btn" class="mt-2 ml-4"><img src="https://img.icons8.com/ios/28/000000/search.png"></i>
                <div class="btn1 sec-search" id="btn1">
                  <form class="form-inline ">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="submit" ><i id="btn" class="m"></i><img src="https://img.icons8.com/ios/28/000000/search.png"></i></button>
                  </form> 
                </div>                                       
              <!-- </div> -->
            </div>
          </div>
      </div>  
    </nav>    
</div>
<div class="create" id="create">
  <form class="form-inline" >
    <input class="form-control search-input mr-sm-2" type="search" placeholder="Search..." aria-label="Search">
    <button class="btn btn-outline-light my-2 my-sm-0 text-dark" type="submit" >Search</button>
  </form>
</div>